# Generated by Django 4.2.16 on 2024-09-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satvik', '0003_reservation_guest_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(),
        ),
    ]
