# Generated by Django 4.2.16 on 2024-09-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satvik', '0004_reservation_special_request_alter_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
